import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import Navbar from "./components/Navbar";
import './styles/globals.css'

export const metadata = {
  title: 'Little Alchemy Recipe Finder',
  description: 'Generated by FullRustAlchemist',
}
const poppins = Poppins({
  subsets: ['latin'],
  weight: ['300', '400'],
})
export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en"
    className={`${poppins.className}`}>
      <body
        className="overflow-x-clip scroll-smooth"
        style={{ scrollBehavior: "smooth" }}
      >
        <div className="flex h-fit min-h-screen w-screen flex-col">
          <Navbar/>
          {children}
        </div>
      </body>
    </html>
  )
}
